name: Test library functionality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set rust to nightly
        run: rustup override set nightly
      - name: Version log
        run: |
          ar --version
          tar --version
          mkdir --version
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build_docs:
    name: Build docs
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set rust to nightly
        run: rustup override set nightly
      - run: cargo doc --no-deps
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
